language: cpp
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dn5Irr/svB2d/iouvSxxoe2SEAWlPUlkNlGWScngWhqSp+kEJ8p3ubQG0ogCK0vGGHPwUYXfIQvHQ8oSc2Z4na8rIwZqvkJnxYYKvPLZpweKhb+xQbpjPwDwEycFDxT+y7mPnRLKRDtdmcuRqMQh8gnxb6TMY9xqlCCvnTfwTmI="
   - coverity_scan_run_condition='"$CC" = gcc'
   - coverity_scan_script_test_mode=false

before_script:
  - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main universe restricted multiverse"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install libboost-all-dev libopenal-dev libmad0-dev libvorbis-dev zlib1g-dev liblzma-dev libwxgtk3.0-0 libwxgtk3.0-dev libpango-1.0-0 libpangocairo-1.0-0
  - export CXXFLAGS="-std=c++0x"

script:
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./autogen.sh; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then ./configure || cat config.log; fi
  - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j4; fi

addons:
  coverity_scan:
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis_coverity.sh
    project:
      name: $TRAVIS_REPO_SLUG
    notification_email: drmccoy@drmccoy.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - ndbrandes@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - secure: "jPAkI6da6HEi+7KfiojReS3EQL1NnuQAe98Lv6dU9UMCsGR9bDMbzE0dMs8BU80MLsPFjy5OKBG0WMXTr43Los/igG9YG5g3VmYuV4w8D1+hjKbcDTxsUwusHz70W1p6NMd3WeWYkgNXRh9wZxAozNoAtouFKkjYlDzMqGAdTSc="
    on_success: change
    on_failure: always
    use_notice: true
